### ISSUE TITLE
Apresentação em Situação Especial

### ISSUE THREAD

**Issue by wagnerlopes** [SERMIL/exarnet#1]
**Problema:** cidadão foi incluído no excesso de contingente e recebeu CDI em situação especial (MFDV, empregado das Empresas de Segurança Nacional, etc) segundo a Lei deve realizar o EXAR durante os cinco anos.

**Sistema:** só está permitindo apresentação de cidadão na situação militar licenciado (15).

**Solução:** Modificar a regra de negócio para permitir apresentação desses cidadãos.

**Comment by andremb2211** [comment]
Já estou verificando Cel @wagnerlopes.

**Comment by andremb2211** [comment]
@romulodba
