### ISSUE TITLE
Preparação da versão 2016 do EXARNET

### ISSUE THREAD

**Issue by wagnerlopes** [SERMIL/exarnet#6]
Corrigir todas as pendências relativas ao EXAR para o corrente ano.

**Comment by andremb2211** [comment]
Bom dia cel @wagnerlopes  a @aryene  já está fazendo esses ajustes.


@romulodba @6975usa

**Comment by aryene** [comment]
Boa tarde Cel @wagnerlopes 
Já fiz algumas correções  conforme o pedido do  Cap @romulodba  seguindo as orientações TC Bartz;
segue as correções atualizadas.
-Textos 
-atualização guia do reservista 
- inserção de novos links do  Exar da marinha e da aeronáutica.

![exar](https://cloud.githubusercontent.com/assets/3015989/19979536/f8143e30-a1e1-11e6-9a0c-6ac60497cebf.png)

Também identifiquei um problema quando seleciona o ESTADO, não carrega as CIDADES .
![imgexar](https://cloud.githubusercontent.com/assets/3015989/19979549/0531279a-a1e2-11e6-9dc5-ce1e85230710.png)


@6975usa  @andremb2211
